swagger: '2.0'
info:
  title: Markdown to PDF API
  version: 1.0.0
security:
  - api_key: []
securityDefinitions:
  api_key:
    type: apiKey
    name: x-api-key
    in: header
paths:
  /convert:
    post:
      operationId: convertMarkdownToPdf
      x-google-backend:
        address: #<your-cloud-run-service-url-with-path> e.g. https://md2pdf-xxxxxxxx.us-central1.run.app/convert
        jwt_audience: #<your-cloud-run-service-url> e.g. https://md2pdf-xxxxxxxx.us-central1.run.app
        protocol: h2
      responses:
        '200':
          description: A successful response
          schema:
            type: string
            format: binary
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
x-google-management:
  security:
    rules:
      - selector: "*"
        providers:
          - id: google_service_account
            issuer: # <your-api-gateway-service-account> 
